### ISSUE TITLE
Too much food

### ISSUE THREAD

**Issue by patstovepipe** [Dkendal/battle_snake#4]
Game stops when it can not find a space for food?

**Game Parameters**
![image](https://cloud.githubusercontent.com/assets/2498431/21631014/6a29e3ec-d1eb-11e6-936d-7abf898533cc.png)
**Game Stopped**
![image](https://cloud.githubusercontent.com/assets/2498431/21631018/7b40e842-d1eb-11e6-8e7c-ddec565a198a.png)

**Comment by Dkendal** [comment]
personally not too worried about this as it's what you might call exceptional behaviour.
